services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DJANGO_SETTINGS_MODULE: config.settings.production
    command: >
      sh -c "
      python manage.py migrate --no-input &&
      gunicorn config.wsgi:application --bind 0.0.0.0:8000
      "
    env_file:
      - .env
      - .env.prod
    environment:
      DJANGO_ENV: production
      DJANGO_SETTINGS_MODULE: config.settings.production
    volumes:
      - ./media:/app/media
      - ./staticfiles:/app/staticfiles
    depends_on:
      - db
      - redis
    networks:
      - internal
      - caddy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/healthcheck/"]
      interval: 120s
      timeout: 10s
      retries: 3
      start_period: 60s

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data/
    networks:
      - internal
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 60s
      timeout: 5s
      retries: 3
      start_period: 60s

  redis:
    image: redis:alpine
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis_data:/data
    networks:
      - internal
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 60s
      timeout: 5s
      retries: 3
      start_period: 60s

  celery:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DJANGO_SETTINGS_MODULE: config.settings.production
    command: celery -A config worker -l info
    env_file:
      - .env
      - .env.prod
    environment:
      DJANGO_ENV: production
      DJANGO_SETTINGS_MODULE: config.settings.production
    volumes:
      - ./media:/app/media
    depends_on:
      - api
      - redis
    networks:
      - internal
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://api:8000/healthcheck/"]
      interval: 120s
      timeout: 10s
      retries: 3
      start_period: 60s

  celery-beat:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DJANGO_SETTINGS_MODULE: config.settings.production
    command: celery -A config beat -l info
    env_file:
      - .env
      - .env.prod
    environment:
      DJANGO_ENV: production
      DJANGO_SETTINGS_MODULE: config.settings.production
    depends_on:
      - redis
    networks:
      - internal
    restart: unless-stopped

volumes:
  db_data:
  redis_data:

networks:
  internal:
    driver: bridge
  caddy:
    external: true
