# Generated by Django 5.1.7 on 2025-03-25 08:29

import django.db.models.deletion
import django_ckeditor_5.fields
import parler.fields
import parler.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
        ('uploads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(allow_unicode=True, unique=True)),
            ],
            options={
                'verbose_name': 'G01. Gallery Category',
                'verbose_name_plural': 'G01. Gallery Categories',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.AlterModelOptions(
            name='copyright',
            options={'verbose_name': '_07. Copyright', 'verbose_name_plural': '_07. Copyright'},
        ),
        migrations.AlterModelOptions(
            name='familysite',
            options={'verbose_name': '_06. Family Site', 'verbose_name_plural': '_06. Family Sites'},
        ),
        migrations.AlterModelOptions(
            name='familysitetranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': '_06. Family Site Translation'},
        ),
        migrations.AlterModelOptions(
            name='footersection',
            options={'verbose_name': '_04. Footer Section', 'verbose_name_plural': '_04. Footer Sections'},
        ),
        migrations.AlterModelOptions(
            name='footersectiontranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': '_04. Footer Section Translation'},
        ),
        migrations.AlterModelOptions(
            name='footersubmenu',
            options={'verbose_name': '_05. Footer SubMenu', 'verbose_name_plural': '_05. Footer SubMenus'},
        ),
        migrations.AlterModelOptions(
            name='footersubmenutranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': '_05. Footer SubMenu Translation'},
        ),
        migrations.AlterModelOptions(
            name='navigationgroup',
            options={'verbose_name': '_02. Navigation Group', 'verbose_name_plural': '_02. Navigation Groups'},
        ),
        migrations.AlterModelOptions(
            name='navigationgrouptranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': '_02. Navigation Group Translation'},
        ),
        migrations.AlterModelOptions(
            name='navigationsubmenu',
            options={'verbose_name': '_03. Navigation SubMenu', 'verbose_name_plural': '_03. Navigation SubMenus'},
        ),
        migrations.AlterModelOptions(
            name='navigationsubmenutranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': '_03. Navigation SubMenu Translation'},
        ),
        migrations.AlterModelOptions(
            name='sitetitle',
            options={'verbose_name': '_01. Site Title', 'verbose_name_plural': '_01. Site Titles'},
        ),
        migrations.AlterModelOptions(
            name='sitetitletranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': '_01. Site Title Translation'},
        ),
        migrations.AddField(
            model_name='news',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='GalleryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(blank=True, null=True, verbose_name='연도')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_featured', models.BooleanField(default=False, verbose_name='메인 표시 여부')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='표시 순서')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gallery_items', to='homepage.gallerycategory')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='homepage_gallery_images', to='uploads.media', verbose_name='갤러리 이미지')),
            ],
            options={
                'verbose_name': 'G02. Gallery Item',
                'verbose_name_plural': 'G02. Gallery Items',
                'ordering': ['order', '-year', '-created_at'],
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='GalleryCategoryTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(max_length=100, verbose_name='카테고리 이름')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='homepage.gallerycategory')),
            ],
            options={
                'verbose_name': 'G01. Gallery Category Translation',
                'db_table': 'homepage_gallerycategory_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='GalleryItemTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('short_description', models.CharField(blank=True, max_length=300, null=True, verbose_name='간략한 설명')),
                ('description', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='상세 설명')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='homepage.galleryitem')),
            ],
            options={
                'verbose_name': 'G02. Gallery Item Translation',
                'db_table': 'homepage_galleryitem_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
