# Generated by Django 5.1.4 on 2025-02-21 13:05

import django.db.models.deletion
import django_ckeditor_5.fields
import parler.fields
import parler.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
        ('uploads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(allow_unicode=True, unique=True)),
            ],
            options={
                'verbose_name': 'E01. Event Category',
                'verbose_name_plural': 'E01. Event Categories',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='NewsCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(allow_unicode=True, unique=True)),
            ],
            options={
                'verbose_name': 'N01. News Category',
                'verbose_name_plural': 'N01. News Categories',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ResourceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(allow_unicode=True, unique=True)),
            ],
            options={
                'verbose_name': 'R01. Resource Category',
                'verbose_name_plural': 'R01. Resource Categories',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name': 'A03. Book', 'verbose_name_plural': 'A03. Books'},
        ),
        migrations.AlterModelOptions(
            name='bookcategory',
            options={'verbose_name': 'A02. Book Category', 'verbose_name_plural': 'A02. Book Categories'},
        ),
        migrations.AlterModelOptions(
            name='bookcategorytranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'A02. Book Category Translation'},
        ),
        migrations.AlterModelOptions(
            name='booktranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'A03. Book Translation'},
        ),
        migrations.AlterModelOptions(
            name='character',
            options={'verbose_name': 'A04. Character', 'verbose_name_plural': 'A04. Characters'},
        ),
        migrations.AlterModelOptions(
            name='charactertranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'A04. Character Translation'},
        ),
        migrations.AlterModelOptions(
            name='copyright',
            options={'verbose_name': 'G07. Copyright', 'verbose_name_plural': 'G07. Copyright'},
        ),
        migrations.AlterModelOptions(
            name='creator',
            options={'verbose_name': 'A01. Creator', 'verbose_name_plural': 'A01. Creators'},
        ),
        migrations.AlterModelOptions(
            name='creatortranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'A01. Creator Translation'},
        ),
        migrations.AlterModelOptions(
            name='familysite',
            options={'verbose_name': 'G06. Family Site', 'verbose_name_plural': 'G06. Family Sites'},
        ),
        migrations.AlterModelOptions(
            name='familysitetranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'G06. Family Site Translation'},
        ),
        migrations.AlterModelOptions(
            name='footersection',
            options={'verbose_name': 'G04. Footer Section', 'verbose_name_plural': 'G04. Footer Sections'},
        ),
        migrations.AlterModelOptions(
            name='footersectiontranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'G04. Footer Section Translation'},
        ),
        migrations.AlterModelOptions(
            name='footersubmenu',
            options={'verbose_name': 'G05. Footer SubMenu', 'verbose_name_plural': 'G05. Footer SubMenus'},
        ),
        migrations.AlterModelOptions(
            name='footersubmenutranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'G05. Footer SubMenu Translation'},
        ),
        migrations.AlterModelOptions(
            name='historyevent',
            options={'ordering': ['date'], 'verbose_name': 'A05. History Event', 'verbose_name_plural': 'A05. History Events'},
        ),
        migrations.AlterModelOptions(
            name='historyeventtranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'A05. History Event Translation'},
        ),
        migrations.AlterModelOptions(
            name='licensepage',
            options={'verbose_name': 'A06. License Page', 'verbose_name_plural': 'A06. License Pages'},
        ),
        migrations.AlterModelOptions(
            name='licensepagetranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'A06. License Page Translation'},
        ),
        migrations.AlterModelOptions(
            name='navigationgroup',
            options={'verbose_name': 'G02. Navigation Group', 'verbose_name_plural': 'G02. Navigation Groups'},
        ),
        migrations.AlterModelOptions(
            name='navigationgrouptranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'G02. Navigation Group Translation'},
        ),
        migrations.AlterModelOptions(
            name='navigationsubmenu',
            options={'verbose_name': 'G03. Navigation SubMenu', 'verbose_name_plural': 'G03. Navigation SubMenus'},
        ),
        migrations.AlterModelOptions(
            name='navigationsubmenutranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'G03. Navigation SubMenu Translation'},
        ),
        migrations.AlterModelOptions(
            name='sitetitle',
            options={'verbose_name': 'G01. Site Title', 'verbose_name_plural': 'G01. Site Titles'},
        ),
        migrations.AlterModelOptions(
            name='sitetitletranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'G01. Site Title Translation'},
        ),
        migrations.AlterField(
            model_name='book',
            name='cover_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='homepage_book_covers', to='uploads.media'),
        ),
        migrations.AlterField(
            model_name='character',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='homepage_character_images', to='uploads.media'),
        ),
        migrations.AlterField(
            model_name='creator',
            name='photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='homepage_creator_photos', to='uploads.media'),
        ),
        migrations.AlterField(
            model_name='historyevent',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='homepage_history_images', to='uploads.media'),
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='행사 날짜')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('main_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='homepage_event_main_images', to='uploads.media', verbose_name='메인 이미지')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='homepage.eventcategory')),
            ],
            options={
                'verbose_name': 'E02. Event',
                'verbose_name_plural': 'E02. Events',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='게시 날짜')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('main_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='homepage_news_main_images', to='uploads.media', verbose_name='메인 이미지')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news', to='homepage.newscategory')),
            ],
            options={
                'verbose_name': 'N02. News',
                'verbose_name_plural': 'N02. News',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homepage_resource_files', to='uploads.media', verbose_name='다운로드 파일')),
                ('main_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='homepage_resource_main_images', to='uploads.media', verbose_name='메인 이미지')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resources', to='homepage.resourcecategory')),
            ],
            options={
                'verbose_name': 'R02. Resource',
                'verbose_name_plural': 'R02. Resources',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='EventCategoryTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(max_length=100, verbose_name='카테고리 이름')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='homepage.eventcategory')),
            ],
            options={
                'verbose_name': 'E01. Event Category Translation',
                'db_table': 'homepage_eventcategory_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='EventTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('description', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='설명')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='homepage.event')),
            ],
            options={
                'verbose_name': 'E02. Event Translation',
                'db_table': 'homepage_event_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='NewsCategoryTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(max_length=100, verbose_name='카테고리 이름')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='homepage.newscategory')),
            ],
            options={
                'verbose_name': 'N01. News Category Translation',
                'db_table': 'homepage_newscategory_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='NewsTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('content', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='내용')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='homepage.news')),
            ],
            options={
                'verbose_name': 'N02. News Translation',
                'db_table': 'homepage_news_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ResourceCategoryTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(max_length=100, verbose_name='카테고리 이름')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='homepage.resourcecategory')),
            ],
            options={
                'verbose_name': 'R01. Resource Category Translation',
                'db_table': 'homepage_resourcecategory_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ResourceTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('description', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='설명')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='homepage.resource')),
            ],
            options={
                'verbose_name': 'R02. Resource Translation',
                'db_table': 'homepage_resource_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
