# Generated by Django 5.1.6 on 2025-02-25 06:29

import django.db.models.deletion
import django_ckeditor_5.fields
import parler.fields
import parler.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
        ('uploads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('hero', 'Hero'), ('books', 'New Books'), ('authors', 'Authors'), ('news', 'News'), ('events', 'Events'), ('video', 'Video'), ('custom', 'Custom')], max_length=20, unique=True, verbose_name='섹션 타입')),
                ('layout', models.CharField(choices=[('full', '전체 너비'), ('half', '절반 너비')], default='full', max_length=20, verbose_name='레이아웃')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화 여부')),
                ('order', models.PositiveIntegerField(verbose_name='표시 순서')),
            ],
            options={
                'verbose_name': 'H01. 홈페이지 섹션',
                'verbose_name_plural': 'H01. 홈페이지 섹션들',
                'ordering': ['order'],
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(blank=True, verbose_name='링크')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화 여부')),
                ('order', models.PositiveIntegerField(verbose_name='표시 순서')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='homepage_hero_slides', to='uploads.media', verbose_name='슬라이드 이미지')),
            ],
            options={
                'verbose_name': 'H02. Hero 슬라이드',
                'verbose_name_plural': 'H02. Hero 슬라이드들',
                'ordering': ['order'],
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='HeroSlideTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.CharField(max_length=100, verbose_name='제목')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='homepage.heroslide')),
            ],
            options={
                'verbose_name': 'H02. Hero 슬라이드 Translation',
                'db_table': 'homepage_heroslide_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='HomeSectionTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('content', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='내용')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='homepage.homesection')),
            ],
            options={
                'verbose_name': 'H01. 홈페이지 섹션 Translation',
                'db_table': 'homepage_homesection_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
