# Generated by Django 5.1.7 on 2025-03-27 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_gallerycategory_alter_copyright_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='familysite',
            options={'ordering': ['order'], 'verbose_name': '_06. Family Site', 'verbose_name_plural': '_06. Family Sites'},
        ),
        migrations.AlterModelOptions(
            name='footersection',
            options={'ordering': ['order'], 'verbose_name': '_04. Footer Section', 'verbose_name_plural': '_04. Footer Sections'},
        ),
        migrations.AlterModelOptions(
            name='footersubmenu',
            options={'ordering': ['order'], 'verbose_name': '_05. Footer SubMenu', 'verbose_name_plural': '_05. Footer SubMenus'},
        ),
        migrations.AlterModelOptions(
            name='navigationgroup',
            options={'ordering': ['order'], 'verbose_name': '_02. Navigation Group', 'verbose_name_plural': '_02. Navigation Groups'},
        ),
        migrations.AlterModelOptions(
            name='navigationsubmenu',
            options={'ordering': ['order'], 'verbose_name': '_03. Navigation SubMenu', 'verbose_name_plural': '_03. Navigation SubMenus'},
        ),
        migrations.AddField(
            model_name='familysite',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='footersection',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='footersubmenu',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='navigationgroup',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='navigationsubmenu',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
