# Generated by Django 5.1.7 on 2025-03-27 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_alter_familysite_options_alter_footersection_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='copyright',
            options={'verbose_name': '_05. Copyright', 'verbose_name_plural': '_05. Copyright'},
        ),
        migrations.AlterModelOptions(
            name='familysite',
            options={'ordering': ['order'], 'verbose_name': '_04. Family Site', 'verbose_name_plural': '_04. Family Sites'},
        ),
        migrations.AlterModelOptions(
            name='familysitetranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': '_04. Family Site Translation'},
        ),
        migrations.AlterModelOptions(
            name='footersection',
            options={'ordering': ['order'], 'verbose_name': '_03. Footer Section', 'verbose_name_plural': '_03. Footer Sections'},
        ),
        migrations.AlterModelOptions(
            name='footersectiontranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': '_03. Footer Section Translation'},
        ),
        migrations.AlterModelOptions(
            name='footersubmenu',
            options={'ordering': ['order'], 'verbose_name': 'Footer SubMenu', 'verbose_name_plural': 'Footer SubMenus'},
        ),
        migrations.AlterModelOptions(
            name='footersubmenutranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'Footer SubMenu Translation'},
        ),
        migrations.AlterModelOptions(
            name='navigationsubmenu',
            options={'ordering': ['order'], 'verbose_name': 'Navigation SubMenu', 'verbose_name_plural': 'Navigation SubMenus'},
        ),
        migrations.AlterModelOptions(
            name='navigationsubmenutranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'Navigation SubMenu Translation'},
        ),
        migrations.AlterField(
            model_name='copyright',
            name='text',
            field=models.CharField(max_length=200),
        ),
    ]
