# Generated by Django 5.1.7 on 2025-03-30 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_alter_copyright_options_alter_familysite_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booktranslation',
            name='summary',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='charactertranslation',
            name='bio_summary',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='footersubmenu',
            name='open_in_new_tab',
            field=models.BooleanField(default=False, verbose_name='새 창에서 열기'),
        ),
    ]
