# Generated by Django 5.1.6 on 2025-02-23 09:34

import uploads.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=uploads.models.generate_filename)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(blank=True, help_text='파일의 표시 이름, 수정 가능', max_length=200, null=True)),
                ('is_used_cached', models.BooleanField(default=False, editable=False)),
                ('hash_value', models.CharField(blank=True, max_length=64, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Media File',
                'verbose_name_plural': 'Media Files',
            },
        ),
    ]
