# Generated by Django 5.1.4 on 2025-02-23 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0002_alter_media_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='hash_value',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
